# Plugin information
name: "Simple Object"
description: "Plugin para el manejo de objetos simples y dinamicos."
version: "2.0"
framework_version: "2.0"
dependencies: ""
notes: ""
# Author information
author: "Paul Marclay"
email: "paul.eduardo.marclay@gmail.com"
site: ""
# Legal information
company: "Dolem Labs"
copyright: "(c) 2012 - Paul Marclay"
license: "GNU GENERAL PUBLIC LICENSE"